defaults:
  - env/libero_10@env.train
  - env/libero_10@env.eval
  - model/abot_m0@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - weight_syncer/patch_syncer@weight_syncer
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_plus_10_ppo_abot_m0"
    logger_backends: ["tensorboard"]

  max_epochs: 1000
  max_steps: -1

  only_eval: false
  val_check_interval: -1
  save_interval: 10

  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: true
  kl_penalty: kl
  group_size: 1
  reward_coef: 1.0
  rollout_epoch: 4
  eval_rollout_epoch: -1

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: chunk_level

  update_epoch: 1
  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0.0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: false
  rewards_lower_bound: 0.1
  rewards_upper_bound: 0.9

  sampling_params:
    do_sample: true
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: false

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  train:
    total_num_envs: 16
    max_episode_steps: 480
    max_steps_per_rollout_epoch: 480
    reward_coef: ${algorithm.reward_coef}
    use_fixed_reset_state_ids: true
    use_ordered_reset_state_ids: false
    perturbation_suffix: all
    video_cfg:
      save_video: false
      info_on_video: false
      video_base_dir: ${runner.logger.log_path}/video/train
  eval:
    total_num_envs: 2
    auto_reset: true
    max_episode_steps: 480
    max_steps_per_rollout_epoch: 480    
    ignore_terminations: true
    use_fixed_reset_state_ids: true
    use_ordered_reset_state_ids: true
    perturbation_suffix: all
    video_cfg:
      save_video: false
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: false
  pipeline_stage_num: 1

  model:
    model_path: "path_to_your_model"
    precision: "bf16"

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 16
  global_batch_size: 64
  seed: 1234
  enable_offload: false

  model:
    model_path: "path_to_your_model"
    model_type: "abot_m0"
    precision: "fp32"
    num_action_chunks: 10
    add_value_head: true

  optim:
    lr: 1.0e-5
    value_lr: 1.0e-5
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0
    critic_warmup_steps: 10

  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: true
    mixed_precision:
      param_dtype: "bf16"
      reduce_dtype: "bf16"
      buffer_dtype: "bf16"

reward:
  use_reward_model: false

critic:
  use_critic_model: false
