defaults:
  - env/behavior_skill_library@data
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 1
  component_placement:
    actor: all

runner:
  task_type: sft
  logger:
    log_path: ${runner.output_dir}/${runner.experiment_name}
    project_name: rlinf
    experiment_name: ${runner.experiment_name}
    logger_backends: ["tensorboard"]

  max_epochs: 5
  max_steps: 500 # TODO: remember to setup lr warmup!
  val_check_interval: 50
  save_interval: 500
  print_eval_samples: 5
  experiment_name: behavior_qwen2_5_vlm_sft_agentic
  output_dir: ../results
  resume_dir: null

# train mode
data:
  type: vlm
  dataset_name: "behavior_agentic_sft"
  sft_data_dir: /mnt/public/xzxuan/data/behavior_SFT
  train_data_paths: /mnt/public/xzxuan/data/2025-challenge-demos
  val_data_paths: /mnt/public/xzxuan/data/2025-challenge-demos
  num_workers: 4
  enable_reasoning: true
  enable_memory: true
  simple_skill: true
  eval_ratio: 0.05
  eval_max_new_tokens: 512
  task_names: ["turning_on_radio"]
  skill_subtask_aug: subtask
  # eval_only: val  # uncomment for eval-only mode: val | train | all

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 4
  eval_batch_size: 4
  global_batch_size: 32
  seed: 42

  model:
    model_type: "qwen2.5_vl"
    precision: fp32
    model_path: /mnt/public/xzxuan/models/Qwen2.5-VL-3B-Instruct
    is_lora: False

  optim:
    lr: 2e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0
    lr_scheduler: "cosine"
    total_training_steps: ${runner.max_steps}
    lr_warmup_steps: 40

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "full_shard"
    use_orig_params: False
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: bf16

reward:
  use_reward_model: False

critic:
  use_critic_model: False
