defaults:
  - model/pi0_5@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: 0-3

runner:
  task_type: sft
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "behavior_pi05_vlm_sft"
    logger_backends: ["tensorboard"]

  max_epochs: 20000
  max_steps: 6000
  val_check_interval: 500
  save_interval: 1000
  print_eval_samples: 5
  max_eval_samples: 50

data:
  type: vlm
  dataset_name: "behavior_skill_pi05"
  train_data_paths: "/mnt/public/xzxuan/data/2025-challenge-demos"
  val_data_paths: "/mnt/public/xzxuan/data/2025-challenge-demos"
  max_token_len: 200
  frame_stride: 10
  eval_episode_count: 20
  num_workers: 4

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 4
  eval_batch_size: 4
  global_batch_size: 16
  seed: 42

  model:
    precision: null
    model_path: "/mnt/public/xzxuan/models/pi05_base_pytorch"
    add_value_head: False
    openpi:
      num_images_in_input: 1
      train_expert_only: False
      full_pi05: True
      forward_mode: "vlm"
      max_language_len: 30
      language_temperature: 0.0
      language_loss_weight: 1.0
      action_loss_weight: 1.0

  optim:
    lr: 2.5e-5
    value_lr: 1.55e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 1e-10
    clip_grad: 1.0
    total_training_steps: 6000
    lr_warmup_steps: 200
    lr_scheduler: "cosine"
    num_cycles: 0.5
    min_lr: 0.0

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    use_orig_params: True
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
