defaults:
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 2
  component_placement:
    actor: all

runner:
  task_type: sft
  logger:
    log_path: ${runner.output_dir}/${runner.experiment_name}
    project_name: rlinf
    experiment_name: ${runner.experiment_name}
    logger_backends: ["tensorboard"] # wandb, swanlab

  # sft runner use the len(dataset) as one epoch
  max_epochs: 6000
  max_steps: -1
  # eval the model intenval
  val_check_interval: 50
  # save the model interval
  save_interval: 50
  experiment_name: qwen3_vl_megatron_sft
  output_dir: ../results
  resume_dir: null

data:
  type: vlm
  dataset_name: "robo2vlmsft"
  apply_chat_template: True
  use_chat_template: True
  # if train_data_paths is not None, the sft code will just eval the model
  train_data_paths: "/path/to/Robo2VLM-1/data"
  eval_data_paths: "/path/to/Robo2VLM-1/eval_data"
  prompt_key: "question"
  choice_key: "choices"
  answer_key: "correct_answer"
  image_keys: ["image"]
  max_prompt_length: 1024
  lazy_loading: false
  num_workers: 16
  answer_separator: ""

algorithm:
  adv_type: gae
  sampling_params:
    temperature: 1.0

actor:
  group_name: "ActorGroup"
  training_backend: megatron
  mcore_gpt: True
  spec_name: decoder_gpt

  enable_dp_load_balance: False
  calculate_flops: False

  micro_batch_size: 4
  eval_batch_size: 1
  global_batch_size: 256
  seed: 42

  model:
    megatron_checkpoint: null
    precision: bf16
    add_bias_linear: False
    add_qkv_bias: False
    qk_layernorm: True

    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    expert_model_parallel_size: 8
    expert_tensor_parallel_size: 1

    # MoE related
    moe_router_load_balancing_type: "aux_loss"
    init_method_std: 0.008
    moe_router_pre_softmax: False
    moe_aux_loss_coeff: 0.001

    moe_permute_fusion: True

    model_type: "qwen3_vl_moe"
    model_path: "/path/to/Qwen3-VL-30B-A3B-Instruct"
    is_lora: False
  
    activation: swiglu
    sequence_parallel: False
    # recompute settings
    # recompute_method: block
    # recompute_granularity: selective

    recompute_method: uniform
    recompute_granularity: full
    recompute_num_layers: 1

    seq_length: 1024
    encoder_seq_length: ${actor.model.seq_length}

    normalization: rmsnorm

    position_embedding_type: rope

    apply_rope_fusion: False
    bias_dropout_fusion: False
    persist_layer_norm: False
    bias_activation_fusion: True
    attention_softmax_in_fp32: True
    batch_p2p_comm: False
    variable_seq_lengths: True
    gradient_accumulation_fusion: True
    moe_token_dispatcher_type: alltoall
    use_cpu_initialization: False

  optim:
    optimizer: adam
    bf16: True
    fp16: False
    lr: 1e-5
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    min_lr: 0.0
    weight_decay: 0.01
    use_distributed_optimizer: True
    overlap_grad_reduce: True
    overlap_param_gather: True
    optimizer_enable_pin: false
    overlap_param_gather_with_optimizer_step: False
    clip_grad: 1.0

  lr_sched:
    lr_warmup_fraction: null
    lr_warmup_init: 0.0
    lr_warmup_iters: 200
    min_lr: 0.0
    lr_decay_style: cosine
    lr_decay_iters: ${runner.max_epochs}
    start_weight_decay: 0.01
    end_weight_decay: 0.01
    weight_decay_incr_style: constant

  tokenizer:
    tokenizer_model: /path/to/Qwen3-VL-30B-A3B-Instruct
    use_fast: False
    trust_remote_code: True
    padding_side: 'right'

  megatron:
    mbridge: True
    ddp_bucket_size: null
    distributed_backend: nccl # Support 'nccl' and 'gloo'
    distributed_timeout_minutes: 30
    ckpt_format: torch
    use_dist_ckpt: False
    tp_comm_bootstrap_backend: nccl
    tp_comm_overlap_cfg: null # tp_comm_overlap_cfg.yaml
    use_hf_ckpt: True # if true, will transfer hf model to generate megatron checkpoint and use it for training.
    use_profiler: False # if true, will enable torch profiler when training, pay attention it has influence on performance

reward:
  use_reward_model: False

critic:
  use_critic_model: False