defaults:
  - base_train

cluster:
  num_nodes: 1
  component_placement:
    actor,rollout,reward: all

runner:
  experiment_name: mas_qwen3_4b_hybrid
  output_dir: ./logs/train
  seq_length: 32000  

  max_epochs: 1
  max_steps: -1  

  val_check_interval: 30
  save_interval: 30

algorithm:
  group_size: 8
  n_minibatches: 1

  clip_ratio_low: 0.2
  clip_ratio_high: 0.28
  clip_ratio_c: 10

  loss_scales: ["group_level", "agent_level", "turn_level"] # used for implementing our GRPO alg. Details in `rlinf/algorithms/loss_scales.py`
  advantage_mode: trajectory

agentloop:
  workflow: mas # or sa, mas refers to multi-agent, sa refers to single-agent
  llm_ip: LLM_JUDGE_IP # TODO:(USER) Replace with the actual IP address of the LLM judge server
  llm_port: LLM_JUDGE_PORT # TODO:(USER) Replace with the actual port of the LLM judge server

rollout:
  model:
    model_path: /PATH/TO/MODEL # TODO:(USER) Replace with the actual path to the model checkpoint

tools:
  online: False

data:
  type: wideseek_r1
  rollout_batch_size: 128
  prompt_key: question
  answer_key: answer
  is_markdown: True
  unique_columns: unique_columns 
  train_data_paths: /PATH/TO/TRAIN/DATASET # TODO:(USER) Replace with the actual path to the training dataset
  shuffle: False
  is_hybrid: True
  data_size: -1

actor:
  model:
    megatron_checkpoint: null
    recompute_num_layers: 36

    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 1
    sequence_parallel: True

  megatron:
    use_hf_ckpt: True
    ckpt_convertor:
      model: Qwen3-4B

