task_subtasks:
  turning_on_radio:
    - "move to radio"
    - "pick up radio from coffee table"
    - "press radio"
    - "place radio on coffee table"

skill_library:
  - "move to"
  - "pick up"
  - "press"
  - "place on"
