model_type: "abot_m0"

model_path: "/path/to/abot_m0_checkpoint"

precision: "bf16"
trust_remote_code: true
is_lora: false
lora_rank: 64

action_dim: 7
num_action_chunks: 10
denoising_steps: 4
image_size: [224, 224]
qwen_max_length: 256

add_value_head: true

rl_head_config:
  joint_logprob: false
  noise_method: "flow_sde"
  noise_level: 0.5
  ignore_last: false
  add_value_head: ${actor.model.add_value_head}
  t_eps: 5.0e-2
  disable_dropout: True
  prediction_type: "x1"
